Jenkinsfile
Jenkins now has s390x machines enabled, which don't currently
have a CentOS 7 image on Docker Hub, causing the check to fail.
=> Force header check to run on amd64

debian/changelog
These caused some warnings to be printed when building:
dpkg-gencontrol: warning:     debian/changelog(l8): badly formatted trailer line
LINE:  -- Sebastiaan van Stijn <thajeztah@docker.com>
dpkg-gencontrol: warning:     debian/changelog(l10): found start of entry where expected more change data or trailer
LINE: containerd.io (1.2.12-1) release; urgency=medium
dpkg-gencontrol: warning:     debian/changelog(l10): found end of file where expected more change data or trailer
dpkg-gencontrol: warning:     debian/changelog(l8): badly formatted trailer line
LINE:  -- Sebastiaan van Stijn <thajeztah@docker.com>
The dates added match the time/date of the commit that these
lines were added in (a5e0d7126ac92055e08c978780217a2901d66ad3 and 4c922ae1193c547030f375fb2425b25d1e8d92e5).
=> deb: fix missing dates in changelog

debian/changelog, rpm/containerd.spec
It was a Tuesday, not a Monday 😓
warning: bogus date in %changelog: Mon Aug 27 2019 Sebastiaan van Stijn <thajeztah@docker.com> - 1.2.8-3.1
=> Fix date in changelog

Jenkinsfile, dockerfiles/rpm.dockerfile, rpm/containerd.spec
replaces https://github.com/docker/containerd-packaging/pull/118
=> rpm: add support for building on CentOS 8

dockerfiles/deb.dockerfile
The devscripts package on newer Ubuntu/Debian versions adds a HUGE
amount of new dependencies. Unfortunately we need this package as
it's the only package that provides `mk-build-deps`, but we don't
have to install all recommended packages:
On Ubuntu 20.04, without `--no-install-recommends`:
4 upgraded, 334 newly installed, 0 to remove and 4 not upgraded.
Need to get 100 MB of archives.
After this operation, 445 MB of additional disk space will be used.
And with `--no-install-recommends`;
0 upgraded, 104 newly installed, 0 to remove and 8 not upgraded.
Need to get 25.0 MB of archives.
After this operation, 119 MB of additional disk space will be used.
This patch also sets `DEBIAN_FRONTEND=noninteractive`, to prevent build
hanging if a package (such as `tzdata`) waits for user input …
=> deb: use non-interactive, and no-install-recommends

Jenkinsfile
Carrying https://github.com/docker/containerd-packaging/pull/142, because Jenkins doesn't run with updated changes unless the author has write access
closes https://github.com/docker/containerd-packaging/pull/142
I started working on this in https://github.com/docker/containerd-packaging/pull/151, but using that version now for debugging builds on arm32
=> Jenkinsfile: add Ubuntu 20.04 "focal" (without armhf) (carry #142)

Jenkinsfile
splitting this of from https://github.com/docker/containerd-packaging/pull/151 as it's useful to have information about the environment in which CI is running (for debugging purposes)
=> Jenkinsfile: show information about CI environment

dockerfiles/rpm.dockerfile, rpm/containerd.spec
this fixes installation on CentOS 8
=> rpm: add libseccomp to "requires"

dockerfiles/rpm.dockerfile
This repository is only specified in the aarch64 (arm64) images,
and therefore was not caught in CI.
Bringing back the fix that was previously there, to prevent failures:
#20 0.800 + yum-builddep -y SPECS/containerd.spec
#20 1.135 Loaded plugins: fastestmirror, ovl
#20 1.365 Enabling base-source repository
#20 1.366 Enabling extras-source repository
#20 1.366 Enabling updates-source repository
#20 1.368 Loading mirror speeds from cached hostfile
#20 1.370  * base: d36uatko69830t.cloudfront.net
#20 1.371  * extras: d36uatko69830t.cloudfront.net
#20 1.371  * updates: d36uatko69830t.cloudfront.net
#20 3.063 http://vault.centos.org/altarch/7/extras/Source/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
#20 …
=> CentOS: fix failing repository on aarch64 (arm64)

dockerfiles/rpm.dockerfile
the extra repo was set unconditionally, which caused
Oracle Linux 8 builds to fail, because it doesn't have
that repo.
=> rpm: fix Oracle Linux 8 build

common/common.mk
A default is already defined in the Dockerfile, and it was not passed as build-arg, so unused.
=> Makefile: remove "PACKAGE" variable

Jenkinsfile, Makefile
Detecting BUILD_BASE and BUILD_TYPE involves pulling an image
from Docker Hub and running it, which is not needed for all
targets.
This patch moves these steps to where it's actually needed.
=> Makefile: don't detect BUILD_BASE, BUILD_TYPE unless needed

debian/rules, rpm/containerd.spec
This is an alternative approach for https://github.com/docker/containerd-packaging/pull/141 and the packaging changes in https://github.com/docker/containerd-packaging/pull/124
closes https://github.com/docker/containerd-packaging/pull/141
This allows upstream containerd to define all binaries that
should be built.
With this change, on the release/1.2 branch, the following binaries
are built:
bin/ctr
bin/containerd
bin/containerd-stress
bin/containerd-shim
bin/containerd-shim-runc-v1
And on the release/1.3 branch (and on master), the following binaries
are built:
bin/ctr
bin/containerd
bin/containerd-stress
bin/containerd-shim
bin/containerd-shim-runc-v1
bin/containerd-shim-runc-v2
Effectively, compared to the current build-scripts, these additional
binaries are included: …
=> build all binaries instead of individual targets

common/common.mk, dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile
The master branch requires Go 1.13 or up, but other branches may still expect an older version of Go.
This patch makes the Go version used default to the version that's used in upstream, but allows overriding the version by manually setting the `GOVERSION` make variable.
Also setting a default value for the golang image in the Dockerfiles (defaulting to `golang:latest`)
=> Makefile: follow upstream Go version by default

Jenkinsfile
Ubuntu Disco has reached EOL in January 2020, currently the CI builds are failing.
This PR removes the distro again.
🕺
=> Remove Ubuntu Disco

Makefile
whoops, looks like my previous fix didn't fix it; follow up to https://github.com/docker/containerd-packaging/pull/169
=> Makefile: fix missing source directory (take 2)

Jenkinsfile
The matrix of distro/architectures to build should match the list of docker packages. CentOS on armhf (arm32) was never supported, so let's remove it from the list.
Users are still able to build these packages if needed, but we don't have to run CI for it.
=> Remove CentOS armhf from matrix

Makefile, Makefile.win, common/common.mk
Our internal pipeline has a configuration to override the repository to build from. While it's not currently used, there could be situations where it's usefull (e.g. when building an embargoed security release).
This patch adds a CONTAINERD_REMOTE makefile variable that allows overriding the repository that we fetch the source from.
Also cleaning up the `CONTAINERD_MOUNT` variable, as it didn't serve any use
=> Makefile: allow overriding repository to build from

Makefile, Makefile.win, common/common.mk
This made the makefile slightly cleaner, and could be useful to build from a fork (just as we added for containerd itself)
Before:
time make REF=v1.3.4 checkout
...
Resolving deltas: 100% (30812/30812), done.
19.37 real         2.70 user         3.11 sys
After:
time make REF=v1.3.4 checkout
...
Resolving deltas: 100% (659/659), done.
From https://github.com/containerd/containerd
* tag               v1.3.4     -> FETCH_HEAD
7.95 real         0.57 user         1.12 sys
=> Makefile: use shallow clone, and add RUNC_REMOTE

Makefile.win
Prevent stale images in the local image cache when building
This change was already made on the linux side, but looks like I forgot to stage this change for windows
=> Makefile.win: pull image when building

rpm/containerd.spec
Starting from containerd 1.3, the BUILDTAGS variable is renamed to GO_BUILDTAGS.
Since we still need to release containerd 1.2, this patch reverts to BUILDTAGS.
When switching to containerd 1.3, this patch can be reverted.
cc @thaJeztah
=> rpm: containerd 1.2 compatible BUILDTAGS variable

Makefile, scripts/checkout.sh
Commit 9706347c34524feb83d75a7119ea88311b41e668 changed to shallow clones
but fetching a tag ref does not download the tag itself.
This patch makes sure that the tag (or branch) is downloaded otherwise
fallsback to fetching the commit hash as it did before.
Ref #173
=> Add checkout.sh to handle tags with shallow clones

scripts/checkout.sh
Before:
git init src/github.com/containerd/containerd
git -C src/github.com/containerd/containerd remote add origin "https://github.com/containerd/containerd.git"
...
git -C src/github.com/containerd/containerd fetch --depth 1 origin refs/heads/master:refs/heads/master
After:
git init src/github.com/containerd/containerd
git -C src/github.com/containerd/containerd remote add origin "https://github.com/containerd/containerd.git"
...
git -C src/github.com/containerd/containerd fetch --update-head-ok --depth 1 origin refs/heads/master:refs/heads/master
=> scripts/checkout.sh: fix git fetch when explicitly fetching "master"

Jenkinsfile
- Fedora 30 reached EOL on 2020-05-26: https://fedoraproject.org/wiki/End_of_life
- Ubuntu 19.10 "Eoan Ermine" reached EOL on 2020-07-17: https://wiki.ubuntu.com/Releases
- Debian GNU/Linux 9 "Stretch" reached EOL on 2020-07-06: https://wiki.debian.org/DebianReleases
Note that this only removes these from the Jenkinsfile; it's still possible to build these, but this PR will remove them from the matrix that's built by default in CI
=> Jenkinsfile: remove Fedora 30, Ubuntu 19.10 "Eoan", Debian / Raspbian 9 "stretch"

common/containerd.service
- relates to / addresses https://github.com/docker/for-linux/issues/1062#issuecomment-660916887
- relates to https://github.com/containerd/containerd/pull/4409 Set a default OOM score for containerd
- sets the default OOM-score for containerd to `-999`
We can remove this option once https://github.com/containerd/containerd/pull/4409 is merged, and once docker switches to containerd 1.4.x (or 1.3.x if that PR is backported)
--------------
If containerd is running as a child-process of dockerd, an OOM-score is set for containerd;
systemctl stop docker
systemctl stop containerd
dockerd &
cat /var/run/docker/containerd/containerd.toml | grep oom_score
oom_score = -500
cat /proc/$(pidof containerd)/oom_score_adj
-500
However, if containerd is running as its own service, the default
oom-score …
=> Set OOM-score in systemd unit to prevent containerd being OOM-killed

common/common.mk
alternative to / supersedes https://github.com/docker/containerd-packaging/pull/184
closes https://github.com/docker/containerd-packaging/pull/184
=> Makefile: automatically select default runc version based on vendor.conf

scripts/build-rpm
carry of https://github.com/docker/containerd-packaging/pull/196 with review comments applied
closes https://github.com/docker/containerd-packaging/pull/196
=> Use 'runc_nokmem' build tag for RHEL/CentOS 7.x RPMs

Jenkinsfile
Hi folks,
This is to address the issue I opened, #197.
Ubuntu 20.10 will be out soon (in about "a month plus a week"). This PR adds Ubuntu 20.10 "Groovy Gorilla" to the list of distro releases to build against in the Jenkinsfile.
Consider adding this to be prepared early for the upcoming Ubuntu release. Thanks.
=> Jenkinsfile: Add Ubuntu 20.10 "Groovy Gorilla"

Jenkinsfile
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit 23066b954d57ab4b9d4dab78b0941f2346aa2b66)
=> [1.3] Jenkinsfile: add Fedora 33 (beta) to CI matrix

debian/changelog, rpm/containerd.spec
upstream release notes:
Welcome to the v1.3.9 release of containerd!
The ninth patch release for containerd 1.3 is a security release to address CVE-2020-15257.
See GHSA-36xw-fx78-c5r4 for more details:
https://github.com/containerd/containerd/security/advisories/GHSA-36xw-fx78-c5r4
upstream release notes (https://github.com/containerd/containerd/releases/tag/v1.3.8):
- Fix metrics monitoring of v2 runtime tasks
- Fix nil pointer error when restoring checkpoint
- Fix devmapper device deletion on rollback
- Fix integer overflow on Windows
- Update seccomp default profile
=> release 1.3.9 (fix CVE-2020-15257)

Jenkinsfile
The "dockereng/rhel" repository is private, so make sure credentials are set.
=> Jenkinsfile: use "wrappedNode" to set Docker Hub creds

debian/changelog, rpm/containerd.spec
release 1.4.3 (CVE-2020-15257)
----------------------------------------
upstream release notes:
Welcome to the v1.4.3 release of containerd!
The third patch release for containerd 1.4 is a security release to
address CVE-2020-15257. See GHSA-36xw-fx78-c5r4 for more details:
https://github.com/containerd/containerd/security/advisories/GHSA-36xw-fx78-c5r4
release 1.4.2
----------------------------------------
- Update to containerd 1.4.2
- Update Golang runtime to 1.15.5
Upstream containerd 1.4.2 release notes: https://github.com/containerd/containerd/releases/tag/v1.4.2
Welcome to the v1.4.2 release of containerd!
------------------------------------------------------
The second patch release for containerd 1.4 includes multiple minor fixes
and updates.
Notable Updates
- Fix bug limiting …
=> release 1.4.3 (CVE-2020-15257)

Makefile
noticed this when running `make clean`:
$ make clean
rm -f -r build/
rm -f -f common/containerd.service
rm -f -r artifacts
rm -f -r src
docker builder prune -f --filter until=24h
...
Looks like `$(RM)` already does `-f`, so adding it here was redundant.
=> Makefile: fix double "-f" on remove

debian/control
equivalent of https://github.com/docker/docker-ce-packaging/pull/520 for containerd packaging
dh-systemd has been integrated into debhelper, starting with version 9.20160709,
and has been removed in Debian 11 "bullseye"
This patch updates the control file to not require it as a dependency
on current versions of debian that ship with that version of debhelper
Related discussions:
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822670
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958585
=> deb: make dh-systemd dependency optional as it's deprecated

dockerfiles/deb.dockerfile, scripts/build-deb
relates to https://github.com/docker/containerd-packaging/pull/213#issuecomment-782172567
Debian "unstable" releases use apt caching information to get the codename
see discussion on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845651:
> That's all to say that this bug is (to my belief) actually expected behaviour;
> and fixing it through forcing the codename to be interpreted as "stretch" when
> apt-cache information is unavailable would be wrong. When /etc/debian_version
> contains "potato/sid", the codename is either potato xor sid, and only apt-
> cache can discriminate a testing host from a sid host. Therefore, in such a
> situation, the correct answer is actually "I can't tell", aka "n/a".
From testing, it reads the information from these files:
- …
=> deb: keep '/var/lib/apt/lists/' to allow building for Debian unstable

dockerfiles/deb.dockerfile
~follow-up to https://github.com/docker/containerd-packaging/pull/219 (I'll rebase once that's merged)~ rebased
Running `apt-cache clean` and/or removing `/var/cache/apt` will be a
no-op in most cases (or at least will provide very little differences).
This patch simplifies the cleanup steps, and only keeps steps to remove
package list information (where possible).
Thanks to Tianon Gravi, who pointed out that this is not needed <3
=> deb: simplify cleaning up after apt-get update/install

Jenkinsfile
=> Jenkinsfile: test building Debian 11 "bullseye"

Jenkinsfile
=> Jenkinsfile: test building Raspbian 11 "bullseye"

Jenkinsfile
For some unknown reasons there are Jenkins parameters that are neither defined in Jenkins nor in Jenkinsfile.
ARCHIVE and CONTAINERD_REF were taken from the output of:
https://ci-next.docker.com/teams-core/job/containerd-packaging/job/master/configure
while RUNC_REF was added so we can build a version different from the vendored one in containerd.
=> Jenkins parameters belong to Jenkinsfile

debian/rules, rpm/containerd.spec
(relates to https://github.com/docker/containerd-packaging/pull/225 - when go modules were used, `go get` / `go build` started failing when attempting to download modules)
Go 1.16 more aggressively forces use of go modules, and as a result for some
steps will ignore the vendor directory, causing the build to fail:
make REF=v1.4.2 RUNC_REF=59ad417c14143ae6b34e9cf88cf3f6e9c6d5f9e8 GOVERSION=1.16.0 docker.io/library/ubuntu:bionic
#21 1.417 make[1]: Entering directory '/root/containerd'
#21 1.418 + pwd
#21 1.418 + make -C /go/src/github.com/containerd/containerd --no-print-directory DESTDIR=/root/containerd VERSION=1.4.2 REVISION=b321d358e6eef9c82fa3f3bb8826dca3724c58c6 PACKAGE=containerd.io binaries install
#21 1.579 + bin/ctr
#21 1.587 go: cannot find main module, but found vendor.conf in …
=> Disable go modules (GO111MODULE=off) to force using vendor directory on Go 1.16

dockerfiles/deb.dockerfile
It looks like `ca-certificates` is not up-to-date in the base-images, and is not
updated as part of installing the build-dependencies, causing failiures when
trying to build with Go 1.15 and Go 1.16 (for some reason, it didn't fail when
using Go 1.13?):
First, make sure that the images are up to date;
$ docker pull docker.io/library/golang:1.16
1.16: Pulling from library/golang
Digest: sha256:c9c3bd7c5cb8e58c1b2d15bb0cd7e43569f920659f71a4a993ca534ee185a1b4
Status: Image is up to date for golang:1.16
docker.io/library/golang:1.16
$ docker pull docker.io/library/ubuntu:bionic
bionic: Pulling from library/ubuntu
Digest: sha256:4bc3ae6596938cb0d9e5ac51a1152ec9dcac2a1c50829c74abd9c4361e321b26
Status: Image is up to date for ubuntu:bionic
docker.io/library/ubuntu:bionic
Build the `build-env` …
=> deb: force updating ca-certificates to prevent SSL errors

Jenkinsfile
This reverts commit 8c249eac8b8c9098ae42d1a6d828c1d8912cb702 (https://github.com/docker/containerd-packaging/pull/222).
These parameters are only used in the release pipeline, which has its own Jenkinsfile, and are not used as part of CI in this repository, so there should be no need to have them in the Jenkinsfile.
=> Revert "Jenkins parameters belong to Jenkinsfile"

Makefile, Makefile.win, common/common.mk, scripts/determine-runc-version
The code that was used to automatically select the default version of runc to use for containerd was still assuming the containerd code to have a vendor.conf.
Containerd "master", and v1.5 have switched to go modules, so should now look in the go.mod file to get the recommended / default version.
Also change the order in which we check out source-code, so that the containerd source-code is checked out before we determine the runc version; this allows us to always use the local source of containerd, without having to use curl to get the version from GitHub.
Finally, a small modification was made for the "make validate" target, which now uses a generic "alpine" Golang image, so that validation can be done before the containerd source code was checked out (which was used to detect the Go …
=> Fix detection of default runc version due upstream to switch to go.mod

common/containerd.toml, debian/rules, dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile, rpm/containerd.spec
This reverts commit 37e406ca6302b373b5840b794cf551110ad4d737.
Relates to https://github.com/docker/containerd-packaging/pull/215#discussion_r632804641
> removing this does have some impact on rpm users who are currently overwriting
> the rpm supplied config.toml with their own. This being removed above, causes
> the user supplied override config.toml file also to be deleted, when they upgrade
> to a rpm version with this change. rpm moves the file to.rpmsave/.rpmnew after
> upgrading to the new version with the above change.
Reverting this change (at least temporarily until we figure out an alternative)
is the safest option for now.
=> Revert "remove default "containerd.toml" config file"

debian/changelog, rpm/containerd.spec
depends on https://github.com/docker/containerd-packaging/pull/233
containerd diff: https://github.com/containerd/containerd/compare/v1.4.4...v1.4.5
runc diff: https://github.com/opencontainers/runc/compare/v1.0.0-rc93...v1.0.0-rc94
containerd release notes: https://github.com/containerd/containerd/releases/tag/v1.4.5
- Update runc to rc94
- Fix leaking socket path in runc shim v2
- Fix cleanup logic in new container in runc shim v2
- Fix registry mirror authorization logic in CRI plugin
- Add support for userxattr in overlay snapshotter for kernel 5.11+
runc release notes: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc94
Potentially breaking changes:
- cgroupv1: kernel memory limits are now always ignored, as kmemcg has
been effectively deprecated by the kernel. Users …
=> prepare release v1.4.5

debian/changelog, rpm/containerd.spec
follow-up to https://github.com/docker/containerd-packaging/pull/232
- Update to containerd 1.4.6
- Update runc to v1.0.0-rc95
containerd diff: https://github.com/containerd/containerd/compare/v1.4.5...v1.4.6
runc diff: https://github.com/opencontainers/runc/compare/v1.0.0-rc94...v1.0.0-rc95
containerd release notes: https://github.com/containerd/containerd/releases/tag/v1.4.6
The sixth patch release for containerd 1.4 is a security release to update
runc for CVE-2021-30465
runc release notes: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc95
This release of runc contains a fix for CVE-2021-30465, and users are
strongly recommended to update (especially if you are providing
semi-limited access to spawn containers to untrusted users).
Aside from this security fix, only a few …
=> prepare release v1.4.6

Makefile, common/common.mk, scripts/determine-runc-version
When testing the script locally from a clean state, I noticed that the RUNC_REF
variable was not working as expected, and failed to pick the runc version that
is set in containerd.
This patch fixes the runc version not being detected correctly.
While Make "promises" to expand variables "when used", it actually performs
this earlier than that, so when combining, it evaluates `$(SOME_VAR)` *before*
the target is run....
From the docs: https://www.gnu.org/software/make/manual/html_node/Flavors.html#Flavors
> references are expanded whenever this variable is substituted (in the course
> of expanding some other string). When this happens, it is called recursive expansion.
However, taking the following Makefile:
```make
SOME_VAR=$(shell cat hello)
.PHONY: clean
clean:
@rm hello
.PHONY: together …
```
=> Fix RUNC_REF not being evaluated correctly

scripts/determine-runc-version
This was introduced in e1b2c4a0e7437e63b018829deb4d0e79e8065205 (https://github.com/docker/containerd-packaging/pull/235), where the version that was found is now stored in a variable (runc_ref) for debugging.
However, I forgot to add an "echo" to actually print the version.
Because of that, the script debugs the version it found:
+ git -C src/github.com/containerd/containerd checkout -q refs/tags/v1.4.6
./scripts/checkout.sh src/github.com/opencontainers/runc "$(./scripts/determine-runc-version)"
INFO: detected runc version (v1.0.0-rc95) from script/setup/runc-version
But in the "build" target it shows that it didn't actually print it
(note the missing version missing between `runc :` and `(commit: ...)`):
--------------------------------------------------------------------
Building …
=> Fix missing echo in scripts/determine-runc-version

debian/rules
related: https://github.com/containerd/containerd/pull/5662
containerd commit https://github.com/containerd/containerd/commit/b5f530a15780ee443b8c568200d37d50d0449672 (https://github.com/containerd/containerd/pull/5535, https://github.com/containerd/containerd/pull/5577) changed the handling of PREFIX and DESTDIR. As a result, the location in which the binaries are installed changed.
This patch sets the PREFIX variable to match the old location, so that the build script can work with both the 1.4 and 1.5 release branches of containerd, and with current master/main.
Once the upstream 1.4 and 1.5 release branches become obsolete, we should consider removing the custom PREFIX, and use (pwd)/usr/local/bin instead, and consider using a TEMP dir for the binaries (and set that as DESTDIR).
=> deb: fix use of PREFIX and DESTDIR for changes in containerd

Jenkinsfile
Now that our agents run on a more recent kernel version, problems with seccomp should likely be resolved, so we can enable these for CI.
closes https://github.com/docker/containerd-packaging/pull/185
closes https://github.com/docker/containerd-packaging/pull/151
closes https://github.com/docker/containerd-packaging/pull/142
relates to https://github.com/moby/moby/issues/40734
=> Jenkinsfile: enable armhf builds for ubuntu:focal and above

rpm/containerd.spec
Added check for suse_version to install dependencies.
=> RPM : Update libseccomp dependency name for SLES/openSUSE distros

Makefile, dockerfiles/deb.dockerfile
I don't think there was a specific reason for picking Centos as the default
=> Makefile: use Ubuntu:20.04 as default BUILD_IMAGE

dockerfiles/rpm.dockerfile
relates to https://github.com/docker/containerd-packaging/pull/163
relates to https://github.com/docker/docker-ce-packaging/pull/513
Names of these files changed a couple of times (lowercase/uppercase). And differ between CentOS 7 and CentOS 8:
On CentOS 7:
docker run --rm centos:7 ls -1 /etc/yum.repos.d/
CentOS-Base.repo
CentOS-CR.repo
CentOS-Debuginfo.repo
CentOS-Media.repo
CentOS-Sources.repo
CentOS-Vault.repo
CentOS-fasttrack.repo
CentOS-x86_64-kernel.repo
On CentOS 8, the files were renamed, and now have `-Linux` in their names:
docker run --rm centos:8 ls -1 /etc/yum.repos.d/
CentOS-Linux-AppStream.repo
CentOS-Linux-BaseOS.repo
CentOS-Linux-ContinuousRelease.repo
CentOS-Linux-Debuginfo.repo
CentOS-Linux-Devel.repo
CentOS-Linux-Extras.repo
CentOS-Linux-FastTrack.repo …
=> rpm: fix repository-file names on CentOS

scripts/determine-runc-version
Starting with containerd v1.4.5, and v1.5.0-beta.4, we can now use the
runc-version file:
- https://github.com/containerd/containerd/blob/v1.4.5/script/setup/runc-version
- https://github.com/containerd/containerd/blob/v1.5.0/script/setup/runc-version
There should no longer be a need to build older (patch) releases of the containerd
packages, so we can now remove the fallbacks.
=> scripts/determine-runc-version: remove fallback for older containerd versions

debian/changelog, rpm/containerd.spec
- Update to containerd 1.4.7
- Update runc to v1.0.0
- Update Golang runtime to 1.15.14
containerd:
- diff: https://github.com/containerd/containerd/compare/v1.4.6...v1.4.7
- release notes: https://github.com/containerd/containerd/releases/tag/v1.4.7
runc:
- diff: https://github.com/opencontainers/runc/compare/v1.0.0-rc95...v1.0.0
- release notes: https://github.com/opencontainers/runc/releases/tag/v1.0.0
golang:
- release notes: https://golang.org/doc/devel/release#go1.15
=> prepare release v1.4.7

debian/changelog, rpm/containerd.spec
Update to containerd 1.4.8 to address [CVE-2021-32760][1].
[1]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32760
=> prepare release v1.4.8

debian/changelog, rpm/containerd.spec
- Update to containerd 1.4.9
- Update runc to v1.0.1
Welcome to the v1.4.9 release of containerd!
The ninth patch release for containerd 1.4 updates runc to 1.0.1 and contains
other minor updates.
Notable Updates
- Update runc binary to 1.0.1
- Update pull authorization logic on redirect
- Fix user agent used for fetching registry authentication tokens
=> prepare release v1.4.9

debian/rules, rpm/containerd.spec
relates to https://github.com/containerd/containerd/issues/6016
Using "auto" to work around an issue with a broken vendor package in
containerd;
GO111MODULE=off make -C /go/src/github.com/containerd/containerd --no-print-directory DESTDIR=/root/containerd PREFIX= VERSION=20210916.065010~7ddf5e5 REVISION=7ddf5e52ba738e868b70807797c79c8e54da3497 PACKAGE=containerd.io binaries install
vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/connection/connection.go:33:2:
found import comments "go.opentelemetry.io/otel/exporters/otlp/internal/otlpconfig" (options.go)
and "go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig" (optiontypes.go)
in /go/src/github.com/containerd/containerd/vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig
Using …
=> Use GO111MODULE=auto instead of "off"

debian/changelog, rpm/containerd.spec
- Update to containerd 1.4.10
- Update runc to v1.0.2
- Update Golang runtime to 1.16.8
=> prepare release v1.4.10

dockerfiles/win.dockerfile
similar to https://github.com/docker/containerd-packaging/pull/249
make bin/containerd
+ bin/containerd
go: cannot find main module, but found vendor.conf in C:\gopath\src\github.com\containerd\containerd
to create a module there, run:
go mod init
=> windows: fix go modules setting

debian/changelog, rpm/containerd.spec
Update to containerd 1.4.11 to address CVE-2021-41103
https://github.com/containerd/containerd/releases/tag/v1.4.11
=> prepare release v1.4.11

Jenkinsfile
This PR adds support for Fedora 35, related to https://github.com/docker/for-linux/issues/1298
=> Jenkinsfile: add Fedora 35

debian/changelog, rpm/containerd.spec
Update to containerd 1.4.11 to address CVE-2021-41190
=> prepare release v1.4.12

dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile
full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.0...v2.0.1
- Fix handling multiple definition descriptions
- Fix inline markup causing table cells to split
- Remove escaping tilde character (prevents tildes (`~`) from disappearing).
- Do not escape dash, underscore, and ampersand (prevents ampersands (`&`) from disappearing).
- Ignore unknown HTML tags to prevent noisy warnings
With this, generating manpages becomes a lot less noisy; no more of these:
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
=> Update cpuguy83/go-md2man to v2.0.1

Jenkinsfile
Packages for s390x are built by IBM, and the RHEL image that we used was outdated/broken, so made CI fail.
=> Jenkinsfile: remove s390x steps

Makefile
This allows building packages using base-images from quay.io, for example to
build for CentOS 8 stream (which is not (yet) on Docker Hub);
make quay.io/centos/centos:stream8
tree build
build
└── centos
└── 8
└── x86_64
├── containerd.io-0.20220208.013149~6a628b6-0.el8.src.rpm
└── containerd.io-0.20220208.013149~6a628b6-0.el8.x86_64.rpm
3 directories, 2 files
=> Makefile: add target for quay.io images

common/common.mk
This variable was previously used to generate the `BUILDER_IMAGE` variable, but appears to be unused since commit 018f1b9384e881a8a6157207615a941c15fb15b3 (https://github.com/docker/containerd-packaging/pull/154)
This workaround was added in d1225f65c3cde07915d9c8a116e096b043921d5a (https://github.com/docker/containerd-packaging/pull/140), and from the related PR;
> This is a workaround for golang:1.12.x images where the manifest list is missing
> s390x. With golang:1.13.x or newer this if block can ve removed again.
Some of our Jenkins jobs allow for GOVERSION to be set as parameter but
unconditionally pass the variable when calling `make` from this repository.
The intent of those parameters was to allow overriding the Go version when
building packages, but due to the parameter to be …
=> Makefile: allow GOVERSION to be passed, but being empty

Makefile
This directory is used when CREATE_ARCHIVE=1 is set, but wasn't
cleaned up when runnning `make clean`.
=> Makefile: clean: also remove "archive" directory

debian/changelog, rpm/containerd.spec
- Update containerd to v1.4.13 to address CVE-2022-23648
- Update runc to v1.0.3
- Update Golang runtime to 1.16.15
=> prepare release v1.4.13

Jenkinsfile
Note: Ubuntu 22.04 will be officially released in mid april.
=> Add Ubuntu 22.04.

dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile
CI is testing against upstream's main branch by default, which switched to
go1.18 and no longer supports `go get` to install binaries (so much for
non-breaking changes!).
Switch to use `go install` instead.
#15 [go-md2man 1/1] RUN go get github.com/cpuguy83/go-md2man/v2/@v2.0.1
#15 sha256:3e9f814116626f2999ba8ad0d09eae1119046b63262fd889e4bbd831991c322d
#15 0.626 go: go.mod file not found in current directory or any parent directory.
#15 0.626 	'go get' is no longer supported outside a module.
#15 0.626 	To build and install a command, use 'go install' with a version,
#15 0.626 	like 'go install example.com/cmd@latest'
#15 0.626 	For more information, see https://golang.org/doc/go-get-install-deprecation
#15 0.626 	or run 'go help get' or 'go help install'.
#15 ERROR: executor failed …
=> Dockerfile: use go install instead of go get, for go1.18 compatibility

debian/changelog, rpm/containerd.spec
Update containerd to v1.5.11 to address CVE-2022-24769
not yet release; upstream PR: https://github.com/containerd/containerd/pull/6714
=> prepare release v1.5.11

debian/changelog, rpm/containerd.spec
upstream also updated to go 1.17.8 for the 1.5.11 release
=> changelog: add go 1.17.8 update

scripts/build-deb, scripts/build-rpm, scripts/new-deb-release, scripts/new-rpm-release
macOS uses the BSD flavor of `date`, which does not support the `--rfc-2822` option, causing the script to fail and produce a changelog entry without a date.
The BSD flavor does have `-R` option, which is supported both on GNU and BSD, which provides the equivalent. From the man page on macOS:
-R      Use RFC 2822 date and time output format. This is equivalent to use
'%a, %d %b %Y %T %z' as output_fmt while LC_TIME is set to the
'C' locale .
Before this patch:
./scripts/new-deb-release 1.2.3
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
[-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
...
containerd.io (1.2.3-1) release; urgency=medium
* TODO: Insert release changes here
-- Sebastiaan van Stijn <thajeztah@docker.com>
After …
=> scripts: fix new-deb-release on macOS, and make sure all dates are in UTC

debian/changelog, rpm/containerd.spec
related https://github.com/moby/moby/pull/43433
- Update containerd to v1.6.3
- Update runc to v1.1.1
- Update Golang runtime to 1.17.9
- Update containerd to v1.6.2
- Update runc to v1.1.0
=> prepare release v1.6.3

scripts/validate/fileheader
While CI won't hit this situation, when running make validate
locally, the working directory may contain a src, build, or archive
directory, which is not part of the code in this repo, so does not
have to be validated.
=> make validate: skip artifacts and sources

Jenkinsfile, rpm/containerd.spec
- carries https://github.com/docker/containerd-packaging/pull/270
- closes https://github.com/docker/containerd-packaging/pull/270
Changes;
- do not "provide" runc on CentOS/RHEL >= 8
- do not build btrfs on CentOS/RHEL >= 8
- set the correct build-dependency for BTRFS on SUSE flavors and "others"
=> Also build for CentOS 9.

debian/changelog, rpm/containerd.spec
- Update containerd to v1.6.5
- Update runc to v1.1.2
- Update Golang runtime to 1.17.11
=> prepare release v1.6.5

debian/changelog, rpm/containerd.spec
- Update containerd to v1.6.6 to address CVE-2022-31030
=> prepare release v1.6.6

dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile
All features we use from the "experimental" syntax have been integrated into
the stable front-end, so there's no longer a need to use the experimental one;
switching to latest stable syntax to make sure we use an up-to-date version.
=> Dockerfile: use latest stable syntax instead of experimental

dockerfiles/rpm.dockerfile
- relates to https://github.com/docker/containerd-packaging/pull/288
- addresses https://github.com/docker/containerd-packaging/pull/288#issuecomment-1203809196
It looks like the `createrepo` (meta)package is no longer available on current versions
of the `opensuse/leap:15` image;
#31 [verify-packages 2/8] RUN . /root/.rpm-helpers; install_package createrepo
#31 sha256:2a4f1d9c47a241e657779268aab82bd68c98d9ec24a5d3df57ce6ed4f7f65671
#31 1.811 Loading repository data...
#31 2.618 Reading installed packages...
#31 3.267 'createrepo' not found in package names. Trying capabilities.
#31 3.267 No provider of 'createrepo' found.
#31 ERROR: executor failed running [/bin/sh -c . /root/.rpm-helpers; install_package createrepo]: exit code: 104
Instead there's now 2 flavours available; a C …
=> openSUSE: fix installation of createrepo in validation step

debian/changelog, rpm/containerd.spec
- Update containerd to v1.6.7
- Update runc to v1.1.3
- Update Golang runtime to 1.17.13 to address CVE-2022-32189
=> prepare release v1.6.7

debian/changelog, rpm/containerd.spec
- Update containerd to v1.6.9
- Update Golang runtime to 1.18.7
=> prepare release v1.6.9

debian/changelog, rpm/containerd.spec
- Update containerd to v1.6.10 (https://github.com/containerd/containerd/releases/tag/v1.6.10)
- Update Golang runtime to 1.18.8
=> prepare release v1.6.10

debian/changelog, rpm/containerd.spec
- Update containerd to v1.6.11
- Update Golang runtime to 1.18.9, which includes fixes for CVE-2022-41717, CVE-2022-41720, and CVE-2022-41720.
=> prepare release v1.6.11

debian/changelog, rpm/containerd.spec
- Update containerd to v1.6.12 to address CVE-2022-23471
=> prepare release 1.6.12

Jenkinsfile
Fedora 36 reached EOL on December 13;
https://docs.fedoraproject.org/en-US/releases/eol/
Start testing Fedora 38 (currently still rawhide);
https://fedorapeople.org/groups/schedule/f-38/f-38-key-tasks.html
=> Jenkinsfile: remove Fedora 35, start testing Fedora 38

Jenkinsfile
Not yet released, but freeze was announced;
https://lists.debian.org/debian-devel-announce/2023/01/msg00004.html
=> Jenkinsfile: add Debian 12 "bookworm" (next stable)

debian/control, rpm/containerd.spec
- relates to https://github.com/docker/containerd-packaging/pull/308#issuecomment-1432957713
- relates to https://github.com/containerd/containerd/pull/7933
Containerd (and Moby) now use the Linux kernel headers for btrfs support. These headers are not available on CentOS 7, as support for btrfs was experimental, and now deprecated (removed), which causes builds of containerd main (and 1.7+) to fail:
In file included from vendor/github.com/containerd/btrfs/v2/btrfs.go:21:0:
./btrfs.h:19:2: error: #error "Headers from kernel >= 4.12 are required on compilation time (not on run time)"
#error "Headers from kernel >= 4.12 are required on compilation time (not on run time)"
^
In file included from vendor/github.com/containerd/btrfs/v2/btrfs.go:21:0:
./btrfs.h:22:30: fatal error: …
=> rpm: add conditionals to disable btrfs for CentOS 7 on containerd 1.7 and up

debian/changelog, rpm/containerd.spec
- update containerd binary to v1.6.18, which includes fixes for CVE-2023-25153
and CVE-2023-25173.
- update Golang runtime to 1.19.6, which includes fixes for CVE-2022-41722,
CVE-2022-41725, CVE-2022-41724, and CVE-2022-41723.
release notes: https://github.com/containerd/containerd/releases/tag/v1.6.18
> - Fix OCI image importer memory exhaustion (GHSA-259w-8hf6-59c2)
> - Fix supplementary groups not being set up properly (GHSA-hmfx-3pcx-653p)
> - Revert removal of /sbin/apparmor_parser check
> - Update Go to 1.19.6
full diff: https://github.com/containerd/containerd/compare/v1.6.17...v1.6.18
- update containerd binary to v1.6.17
release notes: https://github.com/containerd/containerd/releases/tag/v1.6.17
> - Add network plugin metrics
> - Update mkdir permission on /etc/cni to 0755 …
=> prepare release 1.6.18

debian/changelog, rpm/containerd.spec
Notable Updates
- Update hcsshim to v0.9.7 to include fix for graceful termination and pause containers
=> prepare release 1.6.19

debian/changelog, rpm/containerd.spec
While containerd upstream did not yet update the Go version to 1.19.7, we will be packaging with that version. go1.19.7 contains some security fixes. Those fixes may not affect these binaries, but may still trigger security scanners, so let's update the version.
=> update changelog to include Go 1.19.7

debian/changelog, rpm/containerd.spec
- update containerd binary to v1.6.20.
- update runc binary to v1.1.5, which includes fixes for CVE-2023-25809, CVE-2023-27561, and CVE-2023-28642.
=> prepare release 1.6.20

Jenkinsfile
Ubuntu 23.04 is planned to be released on April 20, but final betas are available now.
=> Add Ubuntu 23.04 "Lunar Lobster"

debian/changelog, rpm/containerd.spec
- update containerd binary to v1.6.21
- update runc binary to v1.1.7
- Update Golang runtime to 1.19.9
=> prepare release 1.6.21

Jenkinsfile, Makefile, README.md, debian/README.md
Ubuntu 18.04 LTS reached end of standard support. Expanded Security Maintenance (ESM) is available, but requires a subscription, and we don't provide packages for those.
- https://wiki.ubuntu.com/Releases
- https://ubuntu.com//blog/18-04-end-of-standard-support
=> remove Ubuntu 18.04 Bionic Beaver LTS, as it reached end of standard support

Jenkinsfile
- related: https://github.com/docker/docker-ce-packaging/pull/894
=> Jenkinsfile: remove Fedora 36 as it's EOL

Jenkinsfile
Reached EOL on July 20, 2023:
https://lists.ubuntu.com/archives/ubuntu-announce/2023-July/000293.html
=> Jenkinsfile: remove ubuntu 22.10 (Kinetic Kudu) as it reached EOL

Jenkinsfile
- carries / supersedes https://github.com/docker/containerd-packaging/pull/315
- closes https://github.com/docker/containerd-packaging/pull/315
=> Add fedora 39 (not released yet).

Jenkinsfile, dockerfiles/rpm.dockerfile
CentOS Stream 8 will reach its EOL within less than a year ahead of Rocky and Alma:
- CentOS Stream 8: 2024-05-31
- Rocky Linux 8: 2029-05-31
- AlmaLinux 8: 2029
So RPMs for Rocky and Alma have to be built without depending on CentOS Stream.
Part of :
- docker/docker-ce-packaging#933
=> Jenkinsfile: add Rocky Linux and AlmaLinux

Jenkinsfile, dockerfiles/rpm.dockerfile
- pushing https://github.com/docker/containerd-packaging/pull/323 from my account so that Jenkins builds it
=> Jenkinsfile: add Rocky Linux and AlmaLinux [carry 323]

dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile, dockerfiles/win.dockerfile
- relates to https://github.com/docker-library/golang/issues/472
Make sure we don't get unexpected updates of the go toolchain when building.
=> deb, rpm: use GOTOOLCHAIN=local

Jenkinsfile
- follow-up to https://github.com/docker/containerd-packaging/pull/260
- related to https://github.com/docker/containerd-packaging/pull/167
This was added in a80d978479f989f1daafcae9eef94903adce7c7c, because RHEL builds for s390x used a private image on Docker Hub. The s390x builds were disabled, and removed in ff03b26d4f75d1a1cd84f0c4bf6c3f9a7f78b081, so this is no longer needed.
=> Jenkinsfile: remove s390x left-overs

debian/changelog, rpm/containerd.spec
- update containerd binary to v1.6.28.
- update runc binary to v1.1.12, which includes fixes for CVE-2024-21626.
=> prepare release 1.6.28

Jenkinsfile
Ubuntu 23.04 reached EOL on January 25, 2024, so should no longer be used. https://wiki.ubuntu.com/Releases#End_of_Life
=> remove Ubuntu Lunar 23.04, as it's EOL

Jenkinsfile
- carrying the Ubuntu part of https://github.com/docker/containerd-packaging/pull/330
- closes https://github.com/docker/containerd-packaging/pull/330
=> Add Ubuntu 24.04 Noble (not released yet).

debian/rules
This is a quick band-aid; we need to overhaul how we handle architectures in these scripts (and use the Debian base images for Raspbian); but for now this should ensure we force ARMv6 for Raspbian targets.
=> debian: add explicit GOARM for raspbian

debian/changelog, rpm/containerd.spec
- update containerd binary to v1.6.30
- Update Golang runtime to 1.21.8
- addresses https://github.com/docker/containerd-packaging/issues/346
=> prepare release 1.6.30

debian/rules
Debian armhf is armv7 and hard-float, and Raspbian is a rebuild of Debian with armv6 and hard-float. This is done to make use of the BCM2835 FPU, as while the Debian armel (armv5 and soft-float) port works, it does not make full use of the CPU's hardware.
By making this change, our 'armhf' binaries will work on both armv6 and armv7 systems.
=> debian: build armv6 binaries for armhf

debian/changelog, rpm/containerd.spec
- relates to https://github.com/docker/containerd-packaging/issues/346
- temporarily reverts https://github.com/docker/containerd-packaging/pull/347
- Fix builds for Raspbian armhf producing armv7 binaries
- Build Debian armhf binaries as armv6
- Update Golang runtime to 1.21.8
=> prepare release 1.6.28-2

debian/rules
follow-up to https://github.com/docker/containerd-packaging/pull/212. I noticed that we had the `--with systemd` option here as well (see https://github.com/docker/docker-ce-packaging/pull/520#discussion_r555901971)
=> deb: remove redundant " --with systemd" from debian/rules

debian/changelog, rpm/containerd.spec
- update containerd binary to v1.6.31
- Update Golang runtime to 1.21.9
Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>
=> prepare release 1.6.31

Jenkinsfile
CentOS 8 reached EOL and the package repository is no longer live, so removing it from the Jenkinsfile.
=> Jenkinsfile: remove CentOS Stream 8 (EOL: 2024-05-31)

debian/changelog, rpm/containerd.spec
- Update containerd binary to v1.6.33
- Update Golang runtime to 1.21.11, which includes fixes for CVE-2024-24789, CVE-2024-24790.
=> prepare release 1.6.33

Jenkinsfile
It's currently failing, and may need some changes, but as we're planning to move to containerd 1.7 as default, those changes will be made in the master branch first.
Let's skip it in this branch, as it's only used for CI
=> [release/1.6] remove Fedora rawhide

Jenkinsfile, common/common.mk
Try building both the current (v1.7) and main (v2.0) branches.
We currently package 1.7, but use CI in this repository to also verify if the main (2.0) branch builds succesfully using the scripts in this repository.
=> [main] CI: build both release/1.7 and main branches

README.md, debian/README.md, debian/control, debian/rules, dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile, dockerfiles/win.dockerfile, rpm/README.md, rpm/containerd.spec
Now that the main branch is targeting containerd 1.7, there's some bits we can remove.
Both containerd and runc have been a module for some time now, and all
the branches we care about are a module, so there's no need to set the
GO111MODULE env-var.
The official docker image now have GOTOOLCHAIN=local set by default,
so for stages where we build inside that image, we can remove it;
docker image inspect --format='{{ json .Config.Env }}' golang:1.21.11 | jq .
[
"PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"GOLANG_VERSION=1.21.11",
"GOTOOLCHAIN=local",
"GOPATH=/go"
]
Now that we no longer have to take 1.5/1.6 into account, we must
unconditionally disable brtfs for CentOS and RHEL, as no version
provides the Linux kernel headers for btrfs
This …
=> [main] minor cleanup now that this branch is for containerd 1.7+

README.md
looks like this was missed in 0737507e1ed78267c5964a64d8afd7a30b1a55fb (https://github.com/docker/containerd-packaging/pull/361) 🙈 
=> README: fix missing value for RUNC_REF in example

dockerfiles/deb.dockerfile, dockerfiles/rpm.dockerfile
These COPY instructions either copy to an empty directory, so don't depend on existing content, or copy individual files, which also don't depend on what's existing in the directory, so we can use "--link" for these to allow reusing cache.
=> Dockerfile: use COPY --link where suitable

rpm/containerd.spec
Replace some for their equivalent macros. See the [rpm docs for Fedora][1]
- `%{_builddir}` is the equivalent of `%{_topdir}/BUILD`
- `%{_sourcedir}` is the equivalent of `%{_topdir}/SOURCES`
[1]: https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/#_macros_set_for_the_rpm_and_srpm_build_process
=> rpm: update macros used in spec

Jenkinsfile
It looks like there's some changes in rpmbuild, causing the build to fail.
Temporarily disabling rawhide in CI while we look at a fix
relates to:
- https://github.com/docker/containerd-packaging/pull/354#issuecomment-2148423969
- (internal tracking ticket); https://github.com/docker/runtime-team/issues/140 
=> Jenkinsfile: temporarily disable Fedora Rawhide

Jenkinsfile
CentOS 7 [reaches EOL on June 30][1], so we won't be building packages for containerd 1.7. containerd 1.6 packages are still available for the remaining time for those that need it.
This patch removes it from CI in this repository (but could still be built in our release pipeline).
[1]: https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/#centos-linux-7-end-of-life-june-30-2024
=> [main] Jenkinsfile: remove CentOS 7 (EOL 2024-06-30)

debian/changelog, rpm/containerd.spec
runc release  v1.1.13, but containerd v1.7.18 does not yet have this update in their "runc-version" file, which is the version we use as default when building;
https://github.com/containerd/containerd/blob/v1.7.18/script/setup/runc-version
So, instead we'll update the RUNC_REF when building packages, so that we can include the current version of runc.
release notes: https://github.com/opencontainers/runc/releases/tag/v1.1.13
update runc to v1.1.13
=> update release notes to include runc v1.1.13

debian/changelog, rpm/containerd.spec
- Update containerd binary to v1.7.19
- Update Golang runtime to 1.21.12, which includes a fix for CVE-2024-24791.
=> prepare release 1.7.19

scripts/checkout.sh
git ls-remote's <pattern> argument [1] is a glob [2], and matches anything ending with the given string. This is problematic if multiple tags or branches end with the given pattern. In containerd's case, this returns both tags for the main module ("refs/tags/v1.7.19") and 	# the API module ("refs/tags/api/v1.7.19").
To prevent both of those being found, we check if the given reference starts with a "v"; if it does, we can assume it's a tag, and prefix the pattern with "refs/tags/" to make it less ambiguous.
We're using a case statement here to avoid introducing Bashisms.
[1]: https://git-scm.com/docs/git-ls-remote#Documentation/git-ls-remote.txt-ltpatternsgt82308203
[2]: https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-glob
Before this patch:
make REF=v1.7.19 checkout …
=> [main] scripts/checkout.sh: prevent ls-remote from matching multiple tags

Jenkinsfile
backports:
- https://github.com/docker/containerd-packaging/pull/362
- https://github.com/docker/containerd-packaging/pull/370
- https://github.com/docker/containerd-packaging/pull/372
=> [release/1.6 backport] Jenkinsfile: remove CentOS 7, Fedora 38, Debian and Raspbian 10 Buster

dockerfiles/rpm.dockerfile, scripts/.rpm-helpers
dnf is the default for current RPM-based distros now, so moving it
as first choice. We can probably remove the fallback to yum, but
leaving that for a follow-up.
The Dockerfile was still defaulting to use CentOS 7, which is now EOL,
so using CentOS Stream 9 as default.
Also removing code related to old CentOS versions, and switching to
dnf as default.
=> [main] rpm: drop fallbacks for CentOS/RHEL 7, use dnf instead of yum

dockerfiles/rpm.dockerfile
- relates to https://github.com/docker/containerd-packaging/pull/75
This was added as part of 241608f9e17c8c0f3dba2f73b12275a3025ccc39, but
any version of docker (or BuildKit) should be setting the default PATH,
so setting it manually shouldn't be needed
```bash
docker run --rm docker.io/opensuse/leap:15 sh -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
This step did not have a comment describing why we're setting a custom macro.
CentOS, RHEL, and Fedora all use "~/rpmbuild" ("/root/rpmbuild") as default,
but SUSE uses "/usr/src/packages";
```bash
rpm --eval '%{_topdir}'
rpm --eval '%{_rpmdir}'
```
The custom macro align the directory so that we can keep our scripts and
Dockerfile universal;
```bash
echo "%_topdir    /root/rpmbuild" > /root/.rpmmacros
rpm …
```
=> [main] rpm: rpm.Dockerfile: cleanup opensuse stage

Jenkinsfile, Makefile, dockerfiles/rpm.dockerfile
- carries https://github.com/docker/containerd-packaging/pull/342
- closes https://github.com/docker/containerd-packaging/pull/342
Implements passing the username and password through build-secrets instead of build-args
---
> This is a PoC for building RHEL packages assuming that a RHEL username/password is available in the environment.
>
> This is mostly intended for internal use by Docker, as it is assumed that the main utility is performing builds with a 'real RHEL' for enterprise customers. As such, there is currently no verification in this upstream repository.
>
> However, when a unencumbered RHEL-equivalent distribution (e.g. Rocky) is supported, it will make sense to add verification for that distribution and generalize the 'rhel' infrastructure in this repo.
=> [main] rpm: minimal RHEL support (carry #342)

Jenkinsfile
Ubuntu 23.10 reached EOL on July 11, 2024: https://fridge.ubuntu.com/2024/07/17/ubuntu-23-10-mantic-minotaur-reached-end-of-life-on-july-11-2024/
=> [main] remove Ubuntu 23.10 (Mantic Minotaur) (EOL: July 11, 2024)

Jenkinsfile
- backport https://github.com/docker/containerd-packaging/pull/382
Ubuntu 23.10 reached EOL on July 11, 2024: https://fridge.ubuntu.com/2024/07/17/ubuntu-23-10-mantic-minotaur-reached-end-of-life-on-july-11-2024/
(cherry picked from commit 5a97158bc1bee59ca962701a2850347f90f3de46)
=> [release/1.6 backport] remove Ubuntu 23.10 (Mantic Minotaur) (EOL: July 11, 2024)

debian/rules, rpm/containerd.spec
- relates to https://github.com/docker/docker-ce-packaging/pull/1044#issuecomment-2270858888
- relates to https://github.com/containerd/containerd/issues/10553
- relates to https://github.com/opencontainers/runc/pull/4270
runc v1.1.13 introduced an option to customize the version (as printed by the `--version` flag) through a `VERSION` Make variable / environment variable (see [1]).
This variable collided with the `VERSION` environment variable used by containerd for the same purpose, which lead to `runc` binaries built using the version of containerd;
runc --version
runc version 1.7.20
commit: v1.1.13-0-g58aa9203
...
This patch explicitly sets the `VERSION` variable to the version of runc being built when building the binary.
[1]: …
=> [main] deb, rpm: fix runc using incorrect version

dockerfiles/rpm.dockerfile
- relates to https://github.com/docker/containerd-packaging/pull/371#issuecomment-2312344769
go1.21 and up have a patch that enforces the use of ld.gold to work around
a bug in GNU binutils. See;
- https://github.com/golang/go/issues/22040.
- https://github.com/golang/go/commit/cd77738198ffe0c4a1db58352c89f9b2d2a4e85e
Fedora 41 and up has a fixed version of binutils, and no longer requires that
patch, but will fail without ld.gold installed;
/usr/bin/gcc -Wl,-z,now -Wl,-z,nocopyreloc -fuse-ld=gold -o $WORK/b001/exe/a.out -rdynamic /tmp/go-link-1738353519/go.o /tmp/go-link-1738353519/000000.o /tmp/go-link-1738353519/000001.o /tmp/go-link-1738353519/000002.o /tmp/go-link-1738353519/000003.o /tmp/go-link-1738353519/000004.o /tmp/go-link-1738353519/000005.o /tmp/go-link-1738353519/000006.o …
=> [main] rpm: install binutils-gold to work around build failure on Fedora 41 on arm64

Jenkinsfile
- reverts https://github.com/docker/containerd-packaging/pull/368
- (internal tracking ticket); https://github.com/docker/runtime-team/issues/140 
This reverts commit c1625f75251d1b85ecef1d497ae47cc3a83ee719.
=> [main] Revert "Jenkinsfile: temporarily disable Fedora Rawhide"

Jenkinsfile
- carries https://github.com/docker/containerd-packaging/pull/388
- closes https://github.com/docker/containerd-packaging/pull/388
=> [main] feat: build Fedora 41 RPM packages (carry 388)

Jenkinsfile
Ubuntu 24.10 is planned to be released on October 10. https://discourse.ubuntu.com/t/oracular-oriole-release-schedule/36460
Add Ubuntu 24.10 "Oracular Oriole"
=> [main] Add Ubuntu 24.10 "Oracular Oriole"

Jenkinsfile
- relates to https://github.com/moby/moby/issues/48835
Not released yet (planned in "2025"), but we can probably warm up the builds and add it to CI
=> Jenkinsfile: add Debian 13 "trixie" (testing)

Jenkinsfile
- carry https://github.com/docker/containerd-packaging/pull/394
- closes https://github.com/docker/containerd-packaging/pull/394
> The release date is tentatively scheduled for 19th November 2024, so in a bit less than a month. See https://hackmd.io/@centos/Byv1EJJgJg?utm_source=preview-mode&utm_medium=rec for a draft of the future announcement.
> 
> After that date, we shall rename the OCI image tag `stream10-development` into `stream10`.
> 
> **- Description for the changelog**
> 
> Deliver containerd package for CentOS Stream 10.
The release date is tentatively scheduled for 19th November 2024.
**- What I did**
**- How I did it**
=> [main] Add upcoming CentOS Stream 10

Jenkinsfile
@thaJeztah Yesterday RHEL 10 Beta was officially released, and it seems at the same time Red Hat has renamed the CentOS Stream 10 image name to it's final name. See https://quay.io/repository/centos/centos?tab=tags&tag=latest
=> [main] Use the final CentOS Stream 10 OCI image.

debian/changelog, rpm/containerd.spec
- Update containerd binary to v1.7.24
- Update systemd unit to start containerd service after dbus.service
- Update runc binary to v1.2.2
=> [main] prepare release 1.7.24

rpm/containerd.spec
- relates to https://github.com/docker/docker-ce-packaging/issues/1112
- relates to https://github.com/docker/docker-ce-packaging/pull/1135
Update the license fields to use the (now recommented) SPDX identifier;
> https://docs.fedoraproject.org/en-US/legal/allowed-licenses/ lists
> Apache-2.0 as the SPDX identifier and ASL 2.0 as a "Legacy Abbreviation"
> for Apache License 2.0.
=> [main] rpm: use SPDX identifier for License field

Makefile
v0.2.6 was the last version the module was named github.com/kunalkushwaha/ltag.
Update to github.com/containerd/ltag
=> Makefile: Switch to github.com/containerd/ltag

debian/changelog, rpm/containerd.spec
- Update containerd binary to v1.7.26
- Update runc binary to v1.2.5
Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>
=> prepare release 1.7.26

Jenkinsfile
Fedora 40 reached EOL on May 13, 2025;
https://docs.fedoraproject.org/en-US/releases/eol/
=> remove Fedora 40 (EOL)
