Jenkinsfile

Remove Fedora 29, and start testing Fedora 32 and rawhide

---

scripts/.helpers
scripts/.rpm-helpers
scripts/build-deb
scripts/build-rpm
scripts/deb-or-rpm
scripts/determine-base
scripts/gen-go-dl-url
scripts/new-deb-release
scripts/new-rpm-release
scripts/validate/fileheader

use https://github.com/docker/containerd-packaging/pull/156/files?w=1 to view the diff with whitespace-only changes hidden

Fix some linting and formatting issues in scripts

---

Jenkinsfile
common/common.mk

Signed-off-by: Stefan Scherer <stefan.scherer@docker.com>

Build s390x again

---

.dockerignore
.gitignore
Jenkinsfile
Makefile
Makefile.win
README.md
common/common.mk
debian/README.md
dockerfiles/deb.dockerfile
dockerfiles/rpm.dockerfile
rpm/README.md
rpm/containerd.spec
scripts/.rpm-helpers
scripts/build-deb
scripts/build-rpm

Lots of changes, so best to look at each individual commit's description

Refactor to build in Dockerfile

---

Makefile

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

Makefile: prune build-cache (older than 24h)

---

Jenkinsfile
dockerfiles/rpm.dockerfile

Signed-off-by: Stefan Scherer <stefan.scherer@docker.com>

Build rhel package for s390x

---

debian/changelog
rpm/containerd.spec

release 1.4.1-1

---

Jenkinsfile

Addresses https://github.com/docker/for-linux/issues/1114

Jenkinsfile: add Fedora 33 (beta) to CI matrix

---

Jenkinsfile

backport of https://github.com/docker/containerd-packaging/pull/205

[1.3 backport] Jenkinsfile: use "wrappedNode" to set Docker Hub creds

---

Jenkinsfile

See also: https://fedoraproject.org/wiki/End_of_life

Fedora 31 is already EOL

---

debian/changelog
rpm/containerd.spec

Add changelog for containerd v1.4.3-2

---

debian/changelog
rpm/containerd.spec

Signed-off-by: Wei Fu <fuweid89@gmail.com>

Add changelog for containerd v1.4.4-1

---

Jenkinsfile

relates to https://github.com/docker/for-linux/issues/1220

Jenkinsfile: add Ubuntu 21.04 "Hirsute Hippo" and Fedora 34

---

Makefile
Makefile.win
NOTICE
common/common.mk
common/containerd.toml
debian/rules
dockerfiles/deb.dockerfile
dockerfiles/rpm.dockerfile
dockerfiles/win.dockerfile
scripts/build-deb
scripts/build-rpm
scripts/checkout.sh
scripts/deb-or-rpm
scripts/determine-base
scripts/determine-runc-version
scripts/new-deb-release
scripts/new-rpm-release
scripts/validate/template/bash.txt
scripts/validate/template/dockerfile.txt
scripts/validate/template/makefile.txt

this is why I generally prefer just not including the year 😂  (technically, they should be changed "per file" and only if significant changes were made during a year, but our header check does not support that)

update years in license headers

---

debian/changelog
rpm/containerd.spec

- Update containerd to v1.5.10

prepare release v1.5.10

---

debian/changelog
rpm/containerd.spec

prepare release v1.6.4

---

debian/changelog
rpm/containerd.spec

- Update containerd to v1.6.8
- Update runc to v1.1.4

prepare release v1.6.8

---

dockerfiles/win.dockerfile

- see https://github.com/golang/go/issues/51007
- see https://github.com/docker/containerd-packaging/pull/293#issuecomment-1289529251

Windows: downgrade MinGW version to work around CGO issue

---

Jenkinsfile

Release information: https://wiki.ubuntu.com/Releases

Jenkinsfile: add Ubuntu 22.10 "Kinetic Kudu"

---

debian/changelog
rpm/containerd.spec

- update containerd binary to v1.6.22
- update runc binary to v1.1.8
- Update Golang runtime to 1.19.11

prepare release 1.6.22

---

debian/changelog
rpm/containerd.spec

two separate commits, but we may consider skipping 1.6.23

prepare release 1.6.23, 1.6.24

---

debian/changelog
rpm/containerd.spec

* update containerd binary to v1.6.25
* update runc binary to v1.1.10
* Update Golang runtime to 1.20.10

prepare release 1.6.25

---

debian/changelog
rpm/containerd.spec

- update containerd binary to v1.6.26
- Update Golang runtime to 1.20.12

prepare release 1.6.26

---

debian/changelog
rpm/containerd.spec

- update containerd binary to v1.6.27
- update runc binary to v1.1.11
- Update Golang runtime to 1.20.13

prepare release 1.6.27

---

debian/changelog
rpm/containerd.spec

- Update containerd binary to v1.6.32
- Update Golang runtime to 1.21.10
**- What I did**
**- How I did it**

prepare release 1.6.32

---

dockerfiles/deb.dockerfile
dockerfiles/rpm.dockerfile

full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.1...v2.0.4

[main] deb, rpm: update to github.com/cpuguy83/go-md2man v2.0.4

---

Makefile

- Part of https://github.com/docker/containerd-packaging/pull/342
This part should already be fine to merge

[main] Makefile: add registry.access.redhat.com to known registries

---

debian/changelog
rpm/containerd.spec

- relates to https://github.com/docker/containerd-packaging/pull/384
- relates to https://github.com/docker/containerd-packaging/pull/385
----
- update the date
- include mention of the fix for runc --version
**- What I did**
**- How I did it**

[main] update 1.7.20 changelog

---

debian/changelog
rpm/containerd.spec

- Update containerd binary to v1.7.23
- Update Golang runtime to 1.22.9

prepare release 1.7.23

---

Jenkinsfile

**- What I did**
**- How I did it**

Jenkinsfile: remove Fedora 39 (EOL: November 12, 2024)

---

dockerfiles/deb.dockerfile
dockerfiles/rpm.dockerfile

full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.4...v2.0.5

deb, rpm: update to github.com/cpuguy83/go-md2man v2.0.5

---

debian/changelog
rpm/containerd.spec

- Update containerd binary to v1.7.25
- Update runc binary to v1.2.4

[main] prepare release 1.7.25

---

Jenkinsfile

- carries, closes https://github.com/docker/containerd-packaging/pull/408

Add Fedora 42 (carry #408)

---

debian/changelog
rpm/containerd.spec

Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>

prepare release v1.7.27

---

dockerfiles/deb.dockerfile
dockerfiles/rpm.dockerfile

full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.5...v2.0.7

deb, rpm: update to github.com/cpuguy83/go-md2man v2.0.7
